[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
twitter_solana = "3jKpG8cWViu9fieUF2pUR29WPVie1Ndm6HbkJfMbUXXw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/thalles/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
